import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');

function extractSummarySection() {
  const start = html.indexOf('<div class="section" data-section-key="campaign-summary">');
  const end = html.indexOf('<div class="section campaign-library-section"', start);
  assert.notEqual(start, -1, 'Expected Campaign Summary accordion to exist');
  assert.notEqual(end, -1, 'Expected Campaign Summary accordion boundary to exist');
  return html.slice(start, end);
}

function extractFunction(name) {
  const start = html.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `Expected ${name} to exist`);
  const bodyStart = html.indexOf('{', start);
  let depth = 0;
  for (let i = bodyStart; i < html.length; i += 1) {
    if (html[i] === '{') depth += 1;
    if (html[i] === '}') depth -= 1;
    if (depth === 0) return html.slice(start, i + 1);
  }
  throw new Error(`Could not extract ${name}`);
}

const summarySection = extractSummarySection();

test('Campaign Summary renders as a collapsed accordion section', () => {
  assert.doesNotMatch(html, /<div class="summary-action">/);
  assert.match(summarySection, /<div class="section-hdr collapsed" onclick="toggleSec\(this\)">/);
  assert.match(summarySection, /<h3><svg class="section-icon"[\s\S]*?<\/svg>Campaign Summary<\/h3><span class="section-toggle">▾<\/span>/);
  assert.match(summarySection, /<div class="section-body hidden">/);
  assert.doesNotMatch(summarySection, /<button class="abtn navy" id="open-summary-btn"/);
});

test('Campaign Summary accordion contains existing summary content container and actions', () => {
  assert.match(summarySection, /<div class="summary-body" id="summary-inline-content"><\/div>/);
  assert.match(summarySection, /copyAllUtms\(\)">Copy All UTMs/);
  assert.doesNotMatch(summarySection, /Open Summary|Reset Offer|resetOffer\(\)/);
});

test('Campaign Summary modal remains available for existing shortcut behaviour', () => {
  assert.match(html, /<div class="modal-overlay" id="summary-modal"/);
  assert.match(html, /<h2 id="summary-title">Campaign Summary<\/h2>/);
  const openSummary = extractFunction('openSummary');
  assert.match(openSummary, /document\.getElementById\("summary-modal"\)/);
  assert.match(openSummary, /document\.getElementById\("summary-content"\)/);
  assert.match(openSummary, /content\.innerHTML=getCampaignSummaryHtml\(\);/);
  assert.match(openSummary, /modal\.classList\.add\("active"\);/);
});

test('existing Campaign Summary content is generated by shared renderer', () => {
  const renderer = extractFunction('getCampaignSummaryHtml');
  assert.match(renderer, /getCampaignHealthReviewHtml\(\)/);
  assert.match(renderer, /isOfferLoaded\(o\)/);
  assert.match(renderer, /Offer \$\{i\+1\} — Empty/);
  assert.match(renderer, /summary-meta/);
  assert.match(renderer, /summary-grid/);
  assert.match(extractFunction('renderCampaignSummaryInto'), /getCampaignSummaryHtml\(\)/);
});

test('Reset Offer function remains available but is not rendered in the summary accordion', () => {
  const resetOffer = extractFunction('resetOffer');
  assert.match(resetOffer, /title:"Reset Offer\?"/);
  assert.doesNotMatch(summarySection, /resetOffer\(\)/);
});

test('sticky Save Campaign remains wired to existing campaign save behaviour', () => {
  assert.match(html, /<div class="sb-actions">[\s\S]*<button class="abtn gold" type="button" onclick="saveCampaignFile\(\)">Save Campaign<\/button>/);
  const saveCampaignFile = extractFunction('saveCampaignFile');
  assert.match(saveCampaignFile, /const fileName=buildCampaignFilename\(\);/);
  assert.match(saveCampaignFile, /const payload=buildCampaignFilePayload\(\);/);
  assert.match(saveCampaignFile, /showSessionFeedback\("Campaign saved",false\);/);
  assert.match(saveCampaignFile, /addCampaignHistoryEntry\(buildCampaignHistoryEntryFromPayload\(payload, "saved"\)\);/);
});
